### ISSUE TITLE
PCA/SVD/NMF

### ISSUE THREAD

**Issue by bllchmbrs** [anabranch/mlproject#3]
http://scikit-learn.org/stable/auto_examples/plot_digits_pipe.html#example-plot-digits-pipe-py

**Comment by anabranch** [comment]
http://scikit-learn.org/stable/auto_examples/plot_digits_pipe.html#example-plot-digits-pipe-py

**Comment by bllchmbrs** [comment]
this pipeline is pretty much all set up, just need to run it on the data

**Comment by bllchmbrs** [comment]
would like to add KPCA too
